### ISSUE TITLE
R.compose does not work with Ramda-Fantasy IO

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda#1659]
Here is my scenario, I am modelling a potential scenario you might have working with a web app in the browser, and wish to pull something from a store (which returns an IO), then parse the JSON and determine the user's background-color preference value. I took the idea from Dr Boolean, and have been reworking it with Ramda and Ramda-Fantasy.

This works:

``` js
it('should work with simplistic scenario using compose and map', () => {

      // pretend this is our browser based store object returning an IO
      const Store = new Map();
      Store.set("preferences", IO.of('{"background-color":"#efefef"}'));
      const parsePreferences = map(JSON.parse, Store.get('preferences'));
      const bgPref = map(prop('background-color'), parsePreferences);
      const result = IO.runIO(bgPref);
      expect(result).to.eql('#efefef');

    });
```

But if I try to introduce composition anywhere, as per the example provided by Dr Boolean, then:

``` js
it('should work with simplistic scenario using compose and map - but fails...', () => {

      // pretend this is our browser based store object returning an IO
      const Store = new Map();
      Store.set("preferences", IO.of('{"background-color":"#efefef"}'));
      const getBgColor = compose(prop('background-color'), JSON.parse);
      const bgPref = compose(map(getBgColor), Store.get('preferences'));
      const result = IO.runIO(bgPref());
      expect(result).to.eql('#efefef');

    });
```

this fails.

Error: First argument to _arity must be a non-negative integer no greater than ten
    at _arity (node_modules/ramda/dist/ramda.js:87:19)
    at pipe (node_modules/ramda/dist/ramda.js:7156:16)
    at compose (node_modules/ramda/dist/ramda.js:7412:21)

I have found consistent failure even with simplisitc examples as soon as I attempt to introduce compose.

Please can someone verify expected behaviour? Am I using incorrect implementation of compose, is it a known case that compose doesn't work with IO etc? If need be I can set a breakpoint and start inspecting the ramda source, but I was hoping for a quick reply before doing so if there is a clear explanation.

_(Disclaimer: I don't think this is user error, but cannot rule it out as new to IO in Ramda Fantasy and may be doing something wrong)._

**Comment by arcseldon** [comment]
Thank you!  Programming at 3 am is ok, but shall refrain from asking questions at that hour.

```js
 it('should work with simplistic scenario using compose and map', () => {

      // pretend this is our browser based store object returning an IO
      const Store = new Map();
      Store.set("preferences", IO.of('{"background-color":"#efefef"}'));

      const getBgColor = compose(prop('background-color'), JSON.parse);
      const bgPref = compose(map(getBgColor), () => Store.get('preferences'));
      const result = IO.runIO(bgPref());
      expect(result).to.eql('#efefef');

    });
```

**Comment by arcseldon** [comment]
Ok, I see what I what is going on. This wasn't just down to sleep deprevation afterall. Shall re-open this issue for discussion.

**Comment by arcseldon** [comment]
The examples I was working against use the [Loop Recur IO](https://github.com/loop-recur/hostedjs/blob/master/io.js) library. And that exports a convenience function which does the wrapping of an IO inside a function so that it works seamlessly with compose etc.  However, the slides I was viewing didn't present that information, hence why trying to reproduce using ramda-fantasy failed.

Here is the pertinent code:

```js
var extendFn = function () {
  Function.prototype.toIO = function () {
    var self = this;
    return function (x) {
      var args = arguments;
      return IO(function () {
        return self.apply(this, args)
      });
    };
  };
};
```
This gets exported, so you can just do:

```js
const chai = require('chai'),
  expect = chai.expect,
  R = require('ramda'),
  map = R.map,
  compose = R.compose,
  prop = R.prop,
  RF = require('ramda-fantasy'),
  IO = RF.IO,
  LR = require('./loopRecurIO');

LR.extendFn();
```

And now all functions are capable of `toIO()` upgrade.

Then any IO you want to create, knowing it will become part of a `compose` pipeline can be called, eg:

```js
it('should get text and strip the spaces', () => {

    const getName = function () {
      return 'Ramda Fantasy';
    }.toIO();

    const stripSpaces = function (s) {
      return s.replace(/\s+/g, '');
    };

    const exec = compose(map(stripSpaces), getValue);
    expect(LR.runIO(exec())).to.eql('RamdaFantasy');
  });
```

I am finding myself needing to wrap an IO inside an otherwise redundant function all the time when working with Ramda Fantasy. Not doing so kills the `compose` capability. 

So my question to everyone is should we consider something akin to `extendedFn` above?  Or does that definitely go against the Ramda philosophy? Alternatively, is there a way we could provide a convenience function that does the wrapping without actually polluting the Function.prototype? Should we consider such an api construct.

For reference only, here is a cleaned up (nodejs friendly) version of the looprecur IO implementation:

```js
'use strict';

var runIO = function (io) {
  return io.val.apply(this, [].slice.call(arguments, 1));
};

var IOType = function (fn) {
  this.val = fn;
  this.runIO = this.val;
};

var IO = function (fn) {
  return (new IOType(fn));
};

IOType.of = function (x) {
  return IO(function () {
    return x;
  });
};
IOType.prototype.of = IOType.of;

IOType.prototype.chain = function (g) {
  var io = this;
  return IO(function () {
    return g(io.val()).val();
  });
};

// Derived
IOType.prototype.map = function (f) {
  return this.chain(function (a) {
    return IOType.of(f(a));
  });
};
IOType.prototype.ap = function (a) {
  return this.chain(function (f) {
    return a.map(f);
  });
};

var extendFn = function () {
  Function.prototype.toIO = function () {
    var self = this;
    return function (x) {
      var args = arguments;
      return IO(function () {
        return self.apply(this, args)
      });
    };
  };
};

var inspect = function (x) {
  if (x == null || x == undefined) return "null";
  return x.inspect ? x.inspect() : x.toString();
};

IOType.prototype.inspect = function () {
  return 'IO(' + inspect(this.val) + ')';
};

IOType.prototype.toString = function () {
  return this.inspect();
};

IO.of = function (x) {
  return IO(x).of(x);
};

module.exports = {
  IO,
  runIO,
  extendFn
};
```

**Comment by arcseldon** [comment]
Well, this proves less of a problem IF you have control over the function you wish to IO enable, as you can just wrap internally using `IO.of`, but otherwise it is inconvenient, and a helper would be good.

looprecur.IO and ramda-fantasy.IO equivalents example below:

```js
it('should work with looprecur IO', () => {
      const localStorage = {};
      localStorage.user = JSON.stringify({email: 'ramda@fantasy.io'});

      const getCache = function (x) {
        return Maybe(localStorage[x]);
      }.toIO();

      const getStringEmail = compose(prop('email'), JSON.parse);
      const exec = compose(map(map(getStringEmail)), getCache);
      expect(LR.runIO(exec('user'))).to.eql(Maybe('ramda@fantasy.io'));
    });

    it('should work with ramda fantasy IO', () => {
      const localStorage = {};
      localStorage.user = JSON.stringify({email: 'ramda@fantasy.io'});

      const getCache = function (x) {
        return IO.of(Maybe(localStorage[x]));
      };

      const getStringEmail = compose(prop('email'), JSON.parse);
      const exec = compose(map(map(getStringEmail)), getCache);
      expect(IO.runIO(exec('user'))).to.eql(Maybe('ramda@fantasy.io'));
    });
```
