### ISSUE TITLE
Getting error `R.keys is not a function`

### ISSUE THREAD

**Issue by garajo** [ramda/ramda#2066]
It's with the latest installation. Could this have broken recently?

```
const R = require('rambda')

console.log(R.keys({a: 1, b: 2, c: 3}))

TypeError: R.keys is not a function
    at Object.<anonymous> (/media/gajo/ssd/home/gajo/local/learn/node_packages/rambda/bugreport/index.js:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by jeiea** [comment]
`require('rambda')` → `require('ramda')`
Is it just typo?

**Comment by garajo** [comment]
I totally installed wrong library. https://www.npmjs.com/package/rambda  Thanks

**Comment by CrossEye** [comment]
First I heard of that library -- very interesting!
