### ISSUE TITLE
Wrong Exception if reduce is called with undefined instead of Array

### ISSUE THREAD

**Issue by stheuer** [ramda/ramda#2108]
R.reduce(() => {}, 0, undefined)
TypeError: Cannot read property 'reduce' of undefined
    at _reduce (C:\workspace\secure-access-api\v4\secure-access-api\node_modules\ramda\src\internal\_reduce.js:46:20)
    at Object.f3 [as reduce] (C:\workspace\secure-access-api\v4\secure-access-api\node_modules\ramda\src\internal\_curry3.js:35:16)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)

**Comment by CrossEye** [comment]
Agreed: we have some type-checking and a custom error message on this function.  We shouldn't let this error escape.  

We should probably do something like this in `internal/_reduce.js`:

```patch
     if (isArrayLike(list)) {
       return _arrayReduce(fn, acc, list);
     }
+    if(isNil(list)) {
+      throw new TypeError('reduce: list must be array or iterable');
+    }
     if (typeof list.reduce === 'function') {
       return _methodReduce(fn, acc, list);
     }
```

**Comment by ahmad-reza619** [comment]
hello, is this still up for grabs? @CrossEye are you still working on this? can I take this issue?

**Comment by CrossEye** [comment]
@ahmad-reza619: Feel free to investigate, create a PR.  I haven't looked at it in ages.
