### ISSUE TITLE
Chain seems to break in Node 7.4?

### ISSUE THREAD

**Issue by mrmowgli** [ramda/ramda#2135]
I tried the following code, which I have seen working [here](https://www.youtube.com/watch?v=tN4wyJ9DdtM):

```javascript
const R = require('ramda')

const permissions = {
  'group1-perm1' : true,
  'group1-perm2' : false,
  'group2-perm1' : false,
  'group2-perm2' : true,
  'perm3' : true,
  'perm4' : false
}
  
const addLabel = R.chain(R.head, R.append);

const fn = R.compose(R.map(addLabel), R.toPairs);
console.log(fn(permissions));

```

And I get an exception:

```bash
/home/user/dev/functional/ramda1/node_modules/ramda/src/chain.js:32
    return function(x) { return fn(monad(x))(x); };
                                            ^

TypeError: fn(...) is not a function
    at /home/user/dev/functional/ramda1/node_modules/ramda/src/chain.js:32:45
    at _map (/home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/home/user/dev/functional/ramda1/node_modules/ramda/src/map.js:57:14)
    at /home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_dispatchable.js:39:15
    at /home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_curry2.js:20:46
    at f1 (/home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_curry1.js:17:17)
    at /home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_pipe.js:3:14
    at /home/user/dev/functional/ramda1/node_modules/ramda/src/internal/_arity.js:5:45
    at Object.<anonymous> (/home/user/dev/functional/ramda1/ramda.js:15:13)
    at Module._compile (module.js:571:32)
```

**Comment by mrmowgli** [comment]
User error. Head and append were reversed.
