### ISSUE TITLE
mergeWith oddness

### ISSUE THREAD

**Issue by Sinewyk** [ramda/ramda#2586]
version: 0.25.0
```
> const R = require('ramda');
undefined
> R.mergeWith(R.concat, null, {});
{}
> R.mergeWith(R.concat, {}, null);
{}
> R.mergeWith(R.concat, null, {a: 'a'});
{ a: 'a' }
> R.mergeWith(R.concat, {a: 'a'}, null);
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at _has (REPO/node_modules/ramda/src/internal/_has.js:2:42)
    at mergeWithKey (REPO/node_modules/ramda/src/mergeWithKey.js:38:19)
    at f3 (REPO/node_modules/ramda/src/internal/_curry3.js:47:14)
    at mergeWith (REPO/node_modules/ramda/src/mergeWith.js:31:10)
    at Object.f3 [as mergeWith] (REPO/node_modules/ramda/src/internal/_curry3.js:47:14) 
```

Am I doing something wrong ?

**Comment by buzzdecafe** [comment]
Hmm. I am really sorry that this "works" in the first 3 cases. they should all throw. cc: @CrossEye

**Comment by CrossEye** [comment]
No clue why those work differently.  I will try to look this evening.

**Comment by customcommander** [comment]
Verified and still occurring. Adding tags.
