### ISSUE TITLE
TypeError: 0 is not a function - When using `Array.from` in `pipe` in `every`

### ISSUE THREAD

**Issue by wujido** [ramda/ramda#3209]
I encounter interesting issue. I have situation like this:
```js
    ['str1', 'str2'].every(
        pipe(
            Array.from,
            .
            .
            .
        )
    )
```
This ends with error:
```
<project_path>/node_modules/ramda/src/internal/_arity.js:11
        return fn.apply(this, arguments);
                  ^

TypeError: 0 is not a function
    at from (<anonymous>)
    at <project_path>/node_modules/ramda/src/internal/_arity.js:11:19
    at Array.every (<anonymous>)
    at file:<project_path>/index.js:115:22
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```
I expect to obtain the result of function `every` .

I also found solution to this. Just to add `Identity` to first place in `pipe`
```js
        pipe(
            Identity,
            Array.from,
            .
            .
            .
        )
```
Or to use Ramdas `all`.
But the first case is a bit confusing.

**Comment by customcommander** [comment]
I don't think this is a bug in Ramda.

`Array#every` invokes its callback with three arguments: the current element, its index and the array it belongs to. `Array.from` takes two arguments. The second argument is optional and must be a function.

So this:

```javascript
['str1'].every(pipe(Array.from))
```

… is the same as doing this:

```javascript
['str1'].every((el, idx, arr) => Array.from(el, idx, arr));
```

… which fail because:

```javascript
Array.from('str1', 0, ['str1'])
//                 ^
// Err: 0 is not a function
```

**Comment by wujido** [comment]
Well I can see it now. Thanks for explanation.
