### ISSUE TITLE
compose does not work with zipwith

### ISSUE THREAD

**Issue by kaiser101** [ramda/ramda#3416]
```
import {compose, map, zipWith} from 'ramda'

const nums2 = [1, 2, 3, 4, 5];

const funcs = [
    (x) => x * 2,
    (x) => x * 3,
    (x) => x * 4,
    (x) => x * 5,
    (x) => x * 6,
];

const zipTransform = (a, b) => zipWith((x, y) => x(y))(a)(b);

const add20 = (x) => x + 20;

const finalTransform = compose(map(add20), zipTransform);

const nums4 = finalTransform(funcs)(nums2);

console.log(nums4);
```

This code does not work.  I get the following error.

  var len = Math.min(a.length, b.length);
                                 ^

TypeError: Cannot read properties of undefined (reading 'length')
    at zipWith (E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\zipWith.js:35:34)
    at E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\internal\_curry3.js:30:18
    at E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\internal\_curry2.js:26:18
    at f1 (E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\internal\_curry1.js:19:17)
    at zipTransform (E:\Administrator\Downloads\Code samples\Node\maps.js:87:58)
    at E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\internal\_pipe.js:3:27
    at E:\Administrator\Downloads\Code samples\Node\node_modules\ramda\src\internal\_arity.js:16:19
    at Object.<anonymous> (E:\Administrator\Downloads\Code samples\Node\maps.js:93:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.6.1

**Comment by adispring** [comment]
Maybe because `compose` does not curry the last function automatically.

**Comment by kaiser101** [comment]
Thanks that resolved it for me.
